before:
  hooks:
    - go mod download
builds:
  - id: kubels
    main: ./cmd/kubels
    binary: kubels
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - ppc64le
      - s390x
    goarm: [6, 7]

brews:
  - # GitHub/GitLab repository to push the formula to
    tap:
      owner: semihtok
      name: kubels

    name: kubels
    homepage: https://github.com/semihtok/kubels

    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: semihtok
      email: ibrahim@semihtok.com

    # Caveats for the user of your binary.
    # Default is empty.
    caveats: ""

    # Your app's description.
    # Default is empty.
    description: "kubels (kube ls) is a Kubernetes tool that allows you to list Kubernetes resources with a simple command(s)."

    # SPDX identifier of your app's license.
    # Default is empty.
    license: "MIT"

    # Packages your package depends on.
    dependencies:
      - name: git
      - name: go
checksum:
  name_template: "checksums.txt"
  algorithm: sha256
