before:
  hooks:
    - go mod download
builds:
  - id: kubels
    main: ./cmd/kubels
    binary: kubels
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - ppc64le
      - s390x
    goarm: [6, 7]

brews:
  - # GitHub/GitLab repository to push the formula to
    tap:
      owner: Semih Tok
      name: cli

    name: kubels
    # Template for the url which is determined by the given Token (github or gitlab)
    # Default for github is "https://github.com/<repo_owner>/<repo_name>/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    url_template: "https://github.com/semihtok/kubels/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    homepage: https://github.com/semihtok/kubels

    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: Semih Tok
      email: ibrahim@semihtok.com

    folder: Formula

    # Caveats for the user of your binary.
    # Default is empty.
    caveats: ""

    # Your app's description.
    # Default is empty.
    description: ""

    # SPDX identifier of your app's license.
    # Default is empty.
    license: "MIT"

    # Packages your package depends on.
    dependencies:
      - name: git
      - name: go
checksum:
  name_template: "checksums.txt"
  algorithm: sha256
