# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubels < Formula
  desc "kubels (kube ls) is a Kubernetes tool that allows you to list Kubernetes resources with a simple command(s)."
  homepage "https://github.com/semihtok/kubels"
  version "0.2.0"
  license "Apache 2.0"

  depends_on "git"
  depends_on "go"

  on_macos do
    url "https://github.com/semihtok/kubels/releases/download/v0.2.0/kubels_0.2.0_darwin_amd64.tar.gz"
    sha256 "858cebc3863fde9333b341df41fc2705584ba73fe1179ff41a5b157aace04d0b"

    def install
      bin.install "kubels"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Kubels
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/semihtok/kubels/releases/download/v0.2.0/kubels_0.2.0_linux_armv6.tar.gz"
      sha256 "9a8037f8151e94bf78910e6454d2be4cee209fa03cac2f9624c4529b30cffb91"

      def install
        bin.install "kubels"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/semihtok/kubels/releases/download/v0.2.0/kubels_0.2.0_linux_amd64.tar.gz"
      sha256 "c0b6c13450c2b166845668ffd6d8352e8b1c9e58c01ca6daf69b438d7fb376ff"

      def install
        bin.install "kubels"
      end
    end
  end
end
