# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubels < Formula
  desc "kubels (kube ls) is a Kubernetes tool that allows you to list Kubernetes resources with a simple command(s)."
  homepage "https://github.com/semihtok/kubels"
  version "0.2.0"
  license "Apache 2.0"

  depends_on "git"
  depends_on "go"

  on_macos do
    url "https://github.com/semihtok/kubels/releases/download/v0.2.0/kubels_0.2.0_darwin_amd64.tar.gz"
    sha256 "3111a98731c11a354ff47149e3d2b3e2c6fa6754c5eb1a3d78d07ecc3d5f373c"

    def install
      bin.install "kubels"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Kubels
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/semihtok/kubels/releases/download/v0.2.0/kubels_0.2.0_linux_armv6.tar.gz"
      sha256 "b906d5b5134186984949588163004c7cdb907f0cde76a5c75e84c19c502aa6d9"

      def install
        bin.install "kubels"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/semihtok/kubels/releases/download/v0.2.0/kubels_0.2.0_linux_amd64.tar.gz"
      sha256 "bff253a517e240c526499c0416bdca3b66ae734d1628713d451ca8c4aca3365b"

      def install
        bin.install "kubels"
      end
    end
  end
end
